# Generated by Django 4.2.2 on 2023-12-05 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complete",
        ),
    ]
