# Generated by Django 4.2.2 on 2023-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_remove_task_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
