# Generated by Django 4.2.2 on 2023-12-18 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_alter_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="completed",
        ),
    ]
