# Generated by Django 4.2.2 on 2023-12-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_status_alter_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='status',
        ),
    ]
