# Generated by Django 4.2.2 on 2023-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
