# Generated by Django 4.2.2 on 2023-12-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0010_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="todo.status",
            ),
        ),
    ]
